server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-07-17T21:25:41.621728700+08:00[Asia/Shanghai]
            #- Cookie=username,zd
            #- Header=X-Request-Id, \d+  #请求头里有X-Request-Id属性，且值为整数(正则表达式)
            #- Host=**.atguigu.com
            #- Query=userId, \d+  #请求中 带有userId参数 且参数为整数  ?userId=3
            #- RemoteAddr=192.168.3.1/24
            #- My=gold

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
            #- Path=/gateway/filter/**
#            - Path=/XYZ/abc/{segment}
          filters:
            - My=atzd
#            - RedirectTo=302, http://www.atguigu.com
#            - SetPath=/pay/gateway/{segment}
#            - PrefixPath=/pay
            - AddRequestHeader=X-Request-atzd1,atzdValue1
            - AddRequestHeader=X-Request-atzd2,atzdValue2
#            - RemoveRequestHeader=sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode, Blue111
#            - AddRequestParameter=customerId, 952793
#            - RemoveRequestParameter=customerName
#            - AddResponseHeader=X-Response-atzd, Red
#            - SetResponseHeader=Date, 2099-11-11
#            - RemoveResponseHeader=Content-Type
