server:
  port: 8080

spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          cloud-payment-service:
            connect-timeout: 20000
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048
          mime-types: text/xml,application/xml,application/json #触发请求压缩的数据类型
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true
#Feign接口的日志开启
#logging:
#  level:
#    com:
#      atzd:
#        cloud:
#          apis:
#            PayFeignApi: debug

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50 #设置50%失败时打开断路器
#        sliding-window-type: COUNT_BASED
#        sliding-window-size: 6
#        minimum-number-of-calls: 6 #计算失败率或慢调用率的最小样本
#        automatic-transition-from-open-to-half-open-enabled: true #是否启用自动从开启状态过渡到半开状态
#        wait-duration-in-open-state: 5s #从OPEN 到HALF_OPEN状态需要等待的时间
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#
#    instances:
#      cloud-payment-service:
#        base-config: default


#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50
#        slow-call-duration-threshold: 2s
#        slow-call-rate-threshold: 30
#        sliding-window-type: TIME_BASED
#        sliding-window-size: 2
#        minimum-number-of-calls: 2
#        permitted-number-of-calls-in-half-open-state: 2
#        wait-duration-in-open-state: 5s
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        base-config: default


#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 20s
#  bulkhead:
#    configs:
#      default:
#        max-concurrent-calls: 2
#        max-wait-duration: 1s
#    instances:
#      cloud-payment-service:
#        base-config: default

####resilience4j bulkhead -THREADPOOL的例子
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 20s #timelimiter默认限制远程1s，超过报错不好演示效果所以加上10秒
#  thread-pool-bulkhead:
#    configs:
#      default:
#        core-thread-pool-size: 1
#        max-thread-pool-size: 1
#        queue-capacity: 1
#    instances:
#      cloud-payment-service:
#        baseConfig: default


#resilience4j:
#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 2 #在一次刷新周期内，允许执行的最大请求数
#        limit-refresh-period: 1s #限流器的刷新间隔
#        timeout-duration: 1  #默认等待时间
#    instances:
#      cloud-payment-service:
#        base-config: default


# zipkin图形展现地址和采样率设置
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。